# Numpy is a pyhton library that is used to do the numeraical computing.it works with the dimensionality of the data
      Numpy has different functions to work with the dimensionality of the data

Creating the 1D,2D,3D  arrays

In [3]:
import numpy as np

In [7]:
#1.array : is used to convert the data into dimensions.and it is a collection of homogenous data items
a=np.array([1,2,3,4,5])
b=np.array(['phani','mani','parrot'])
##attributes of numpy
print(a.shape)#to get the number of rows and columns
print(a.size)# to get the number of elements in the array
print(a.ndim)#to get the dimension of the data
print(a.dtype)#to get the type of data
print(a)
print(b)

(5,)
5
1
int32
[1 2 3 4 5]
['phani' 'mani' 'parrot']


In [17]:
#1D
print('---->1D---')
a=np.array([1,2,3,4,5])
print(a)
print('--accessing--')
print(a[3])
#2D
print('---->2D----')
b=np.array([[1,2,3,4],[1,2,3,4]])
print(b)
print('---->accessing2D')
print(b[0][1])
#3D
print('-----<>3D---')
c=np.array([[[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]]])
print(c)
print(c.shape)


---->1D---
[1 2 3 4 5]
--accessing--
4
---->2D----
[[1 2 3 4]
 [1 2 3 4]]
---->accessing2D
2
-----<>3D---
[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]
  [11 12 13 14 15]]]
(1, 3, 5)


In [11]:
#2.arange : is a function in numpyn used to get the numbers in specified range.it gives 1D data
a=np.arange(1,60,2) #(start,stop,step)
print(a.shape)
print(a.size)
print(a.ndim)
print(a)

(30,)
30
1
[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59]


In [20]:
##3.reshape:used to convert the 1D data to nD
print('to convert the data into 2D')
a=np.arange(60).reshape(10,6)#(rows,columns)
print(a)
print()
print('----to covert the data into 3D')
print()
b=np.arange(60).reshape(2,5,6)#(cubes,rows,columns)
print(b)

to convert the data into 2D
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]
 [48 49 50 51 52 53]
 [54 55 56 57 58 59]]

----to covert the data into 3D

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]]

 [[30 31 32 33 34 35]
  [36 37 38 39 40 41]
  [42 43 44 45 46 47]
  [48 49 50 51 52 53]
  [54 55 56 57 58 59]]]


In [21]:
##4.linspace: is used to divide the range of into equal parts
a=np.linspace(10,20,5)
print(a)

[10.  12.5 15.  17.5 20. ]


In [31]:
#5.hstack and vstack :are used to add the data  vertically and horizontally to the rows and columns
a=np.arange(60).reshape(10,6)
print('----before h stack----')
print()
print(a)
print(b)
b=np.arange(61,121).reshape(10,6)
print(a.shape)
print(b.shape)
print()
print('----->after hstack---')
c=np.hstack((a,b))
print(c)
print(c.shape)
print()
print('----->vstack-----')
print()
d=np.vstack((a,b))
print(d.shape)
print(d)

----before h stack----

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 31 32 33 34 35]
 [36 37 38 39 40 41]
 [42 43 44 45 46 47]
 [48 49 50 51 52 53]
 [54 55 56 57 58 59]]
[[ 61  62  63  64  65  66]
 [ 67  68  69  70  71  72]
 [ 73  74  75  76  77  78]
 [ 79  80  81  82  83  84]
 [ 85  86  87  88  89  90]
 [ 91  92  93  94  95  96]
 [ 97  98  99 100 101 102]
 [103 104 105 106 107 108]
 [109 110 111 112 113 114]
 [115 116 117 118 119 120]]
(10, 6)
(10, 6)

----->after hstack---
[[  0   1   2   3   4   5  61  62  63  64  65  66]
 [  6   7   8   9  10  11  67  68  69  70  71  72]
 [ 12  13  14  15  16  17  73  74  75  76  77  78]
 [ 18  19  20  21  22  23  79  80  81  82  83  84]
 [ 24  25  26  27  28  29  85  86  87  88  89  90]
 [ 30  31  32  33  34  35  91  92  93  94  95  96]
 [ 36  37  38  39  40  41  97  98  99 100 101 102]
 [ 42  43  44  45  46  47 103 104 105 106 107 108]
 [ 48  49  50  51  52  53 109 110 111 112 113 1

In [32]:
##6.ravel: is a function in numpy used to convert the any Dimension data to 1D
b=np.array([[1,2,3,4],[1,2,3,4]])
print(b.ravel())

[1 2 3 4 1 2 3 4]


In [40]:
##7.random : is a function in numpy used to give the random values in particular range.it has 4 types
##1.randit  2.random  3.rand  4.randn
a=np.random.randint(1,100,3)#(from,to,count we want)
print(a)
print()
b=np.random.random(3) ##(number of random values)
print(b)
print()
c=np.random.rand(3,3)
print(c)
print()
d=np.random.randn(3,3)
print(d)

[10 13  1]

[0.3830897  0.49407528 0.25341202]

[[0.71744029 0.53361114 0.02136853]
 [0.93030262 0.02683199 0.65056236]
 [0.267771   0.78090539 0.45930396]]

[[ 0.78145317  0.67822717 -1.4194244 ]
 [ 0.39039219 -0.28751257  1.42956967]
 [-0.75065393 -1.27047907 -0.63364162]]


In [63]:
##8.Where : is an important function in numpy used to find the index of the value
a=np.array([1,2,3,4,5])
print(np.where(a==3))

(array([2], dtype=int64),)


In [67]:
a=np.array([1,2,3,4,5])
np.where(a==3 ,4,a) #(condition,x,replacing value)

array([1, 2, 4, 4, 5])

## In Numpy dimensions are called axis
## axis =1 (refers to the rows)
#  axis=0   (refers to the columns)

##matrix methods

In [45]:
a=np.zeros((3,3),dtype=int)
print(a)
print()
b=np.ones((3,3),dtype=int)
print(b)
print()
c=np.diag([1,2,3,4])
print(c)
print()
d=np.eye(3,3)
print(d)


[[0 0 0]
 [0 0 0]
 [0 0 0]]

[[1 1 1]
 [1 1 1]
 [1 1 1]]

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [59]:
a=np.arange(1,10).reshape(3,3)
print(a)
b=np.arange(10,19).reshape(3,3)
print(b)
print(np.add(a,b))
print(np.subtract(a,b))
print(np.divide(a,b))
print(np.multiply(a,b))
print(np.mean(a))
print(np.median(a,axis=1))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[10 11 12]
 [13 14 15]
 [16 17 18]]
[[11 13 15]
 [17 19 21]
 [23 25 27]]
[[-9 -9 -9]
 [-9 -9 -9]
 [-9 -9 -9]]
[[0.1        0.18181818 0.25      ]
 [0.30769231 0.35714286 0.4       ]
 [0.4375     0.47058824 0.5       ]]
[[ 10  22  36]
 [ 52  70  90]
 [112 136 162]]
5.0
[2. 5. 8.]


In [61]:
a=np.full((4,4),3,dtype=int)
print(a)

[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


# filtering the values

In [69]:
a=np.array([40,50,60,70,79])
new_arr=[]
for i in a:
    if i>50:
        new_arr.append(i)
print(new_arr)

[60, 70, 79]
